
services:
  php:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    restart: on-failure
    volumes:
      - .:${WORKING_DIR}
    working_dir: ${WORKING_DIR}
    user: "${USER_ID}:${GROUP_ID}"
    extra_hosts:
      - ${WORKING_NET}:host-gateway
    environment:
      USER_ID: $USER_ID
      GROUP_ID: $GROUP_ID
      PHP_IDE_CONFIG: serverName=phpserver
      XDEBUG_CONFIG: client_host=${NET_HOST} output_dir = ${WORKING_DIR}/var/xdebug
#     XDEBUG_MODE: debug,profile
      XDEBUG_MODE: debug,coverage
    command: php -S 0.0.0.0:8080 -t /app/public
    ports:
      - "8080:8080"

